"use strict";
var foreignKeyBuilder_1 = require("./foreignKeyBuilder");
exports.ConfigBuilderColumnConfig = {
    ColumnConfiguration: [
        {
            "dbColumnName": "dbColumnName",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Column Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "htmlControlType",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "updatedValue Type",
            "dataSourceAddress": { dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": [{ Id: "text", Description: "text" }, { Id: "select", Description: "select" }, { Id: "datetime-local", Description: "datetime-local" },
                { Id: "checkbox", Description: "checkbox" }, { Id: "number", Description: "number" }],
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "isVisible",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Visible",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "isRequired",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Required",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "isComplexType",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Complex Type",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "displayName",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Display Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "dataSourceAddress",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isComplexTypeInline": true,
            "isComplexTypeInlineTemplate": [{ tableName: "", dbColumnName: "", displayColumnName: "" }],
            "isComplexTypeInlineTemplateConfig": foreignKeyBuilder_1.ForeignKeyBuilderConfig,
            "isRequired": true,
            "displayName": "Foreign Key",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": true,
            "isToggleable": false,
        },
        {
            "dbColumnName": "dataSource",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isComplexTypeInline": false,
            "isRequired": true,
            "displayName": "Foreign Key Selection",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "regex",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": true,
            "displayName": "Regular Expression",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": true,
            "isToggleable": false
        },
        {
            "dbColumnName": "columnCss",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": true,
            "displayName": "Column CSS Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false
        },
        {
            "dbColumnName": "isAllowGridLevelEdit",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Allow Grid Level Edit",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "isToggleable",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Toggleable",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        }]
};
//# sourceMappingURL=configBuilderColumnConfig.js.map