"use strict";
exports.ConfigBuilderPageConfig = {
    ColumnConfiguration: [
        {
            "dbColumnName": "ChildType",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Edit Type",
            "dataSourceAddress": { dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": [{ Id: "edit", Description: "edit" }, { Id: "editInline", Description: "editInline" }],
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "PrimaryKeyColumn",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Primary Key Column",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "ForeignKeyColumn",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Foreign Key Column",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        },
        {
            "dbColumnName": "ShallHideDeleteButton",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Hide Delete Button",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "ShallHideAddButton",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Hide Add Button",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "IsChildPage",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Is Child Type",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "ShowFilterRow",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Show Filter Row",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        }, {
            "dbColumnName": "PaginationPageLimit",
            "htmlControlType": "numeric",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Pagination page limit",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[0-9]*$",
            "isAllowGridLevelEdit": false,
            "isToggleable": false,
        }
    ] };
//# sourceMappingURL=configBuilderPageConfig.js.map