let TheChild = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ForeignKeyColumn: "UserId",
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    {
        "dbColumnName": "RoleId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Role",
        "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Description" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-6",
    },
    {
        "dbColumnName": "UserId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "User",
        "dataSourceAddress": { tableName: "/auth/User", dbColumnName: "Id", displayColumnName: "Login" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-6",
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": true,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }]
};

export var UserControlConfig = {
    ChildType: "editInline",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    IsChildPage: "true",
    childControlconfig: TheChild,
    PaginationPageLimit: 10,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required":false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":undefined,
    },
    {
        "dbColumnName": "Name",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Name",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-6",
    },
    {
        "dbColumnName": "Login",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "UserName",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-5",
    },
    {
        "dbColumnName": "CostCentre",
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required":true,
        "displayName": "Cost Centre",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-3",
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required":true,
        "displayName": "VersionStamp",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-3",
    }]
};