
import {ForeignKeyBuilderConfig} from "./foreignKeyBuilder";
export var ConfigBuilderColumnConfig = {

    ColumnConfiguration: [
        {
            "dbColumnName": "dbColumnName",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Column Name",
            "displayOrder": 1,
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "htmlControlType",
            "htmlControlType": "select",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Control Type",
            "displayOrder": 7,
            "dataSourceAddress": {dbColumnName:"Id", displayColumnName:"Description"},
            "dataSource": [{Id:"text",Description:"text"},{Id:"select",Description:"select"},{Id:"datetime-local",Description:"datetime-local"},
                {Id:"checkbox",Description:"checkbox"}, {Id:"number",Description:"number"}],
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "visiblity",
            "htmlControlType": "checkbox",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Visibility",
            "displayOrder": 4,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "required",
            "htmlControlType": "checkbox",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Required",
            "displayOrder": 5,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "isComplexType",
            "htmlControlType": "checkbox",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Complex Type",
            "displayOrder": 6,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "displayName",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Display Name",
            "displayOrder": 2,
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit": false,
            "togglable": false,
        },
        {
            "dbColumnName": "displayOrder",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Display Order",
            "displayOrder": 3,
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit": false,
            "togglable": false,
        },
        {
            "dbColumnName": "dataSourceAddress",
            "htmlControlType": "text",
            "visibility": true,
            "isComplexType": false,
            "isComplexTypeInline": true,
            "isComplexTypeInlineTemplate": [{tableName: "",dbColumnName: "", displayColumnName: ""}],
            "isComplexTypeInlineTemplateConfig": ForeignKeyBuilderConfig,
            "required": true,
            "displayName": "Foreign Key",
            "displayOrder": 8,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":true,
            "togglable": false,
        },
        {
            "dbColumnName": "dataSource",
            "htmlControlType": "text",
            "visibility": true,
            "isComplexType": false,
            "isComplexTypeInline": false,
            "required": true,
            "displayName": "Foreign Key Selection",
            "displayOrder": 9,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "regex",
            "htmlControlType": "text",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Regular Expression",
            "displayOrder": 10,
            "dataSourceAddress": undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":true,
            "togglable": false
        },
        {
            "dbColumnName": "columnCss",
            "htmlControlType": "text",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Column CSS Name",
            "displayOrder": 11,
            "dataSourceAddress":  undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false
        },
        {
            "dbColumnName": "allowGridLevelEdit",
            "htmlControlType": "checkbox",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Editable",
            "displayOrder": 12,
            "dataSourceAddress":  undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName": "togglable",
            "htmlControlType": "checkbox",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Toggle",
            "displayOrder": 13,
            "dataSourceAddress":  undefined,
            "dataSource":  undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit":false,
            "togglable": false,
        }]
};



