export  var ConfigBuilderPageConfig={

       ColumnConfiguration: [
           {
               "dbColumnName": "ChildType",
               "htmlControlType": "select",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Edit Type",
               "dataSourceAddress": {dbColumnName:"Id", displayColumnName:"Description"},
               "dataSource": [{Id:"edit",Description:"edit"},{Id:"editInline",Description:"editInline"}],
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "PrimaryKeyColumn",
               "htmlControlType": "text",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Primary Key Column",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "ForeignKeyColumn",
               "htmlControlType": "text",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Foreign Key Column",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "ShallHideDeleteBtn",
               "htmlControlType": "checkbox",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Hide Delete Button",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "shallHideAddBtn",
               "htmlControlType": "checkbox",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Hide Add Button",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "IsChildPage",
               "htmlControlType": "checkbox",
               "visibility": true,
               "required": true,
               "isComplexType": false,
               "displayName": "Is ChildTye",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           },
           {
               "dbColumnName": "PaginationPageLimit",
               "htmlControlType": "numeric",
               "visibility": true,
               "required": false,
               "isComplexType": false,
               "displayName": "Pagination page limit",
               "dataSourceAddress": undefined,
               "dataSource": undefined,
               "regex": "^[0-9]*$",
               "columnCss": "",
               "allowGridLevelEdit":false,
               "togglable": false,
           }
 ]};

