export var ForeignKeyBuilderConfig = {
    ColumnConfiguration: [
        {
            "dbColumnName": "tableName",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Foreign Table Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit": false,
            "togglable": false,
        },
        {
            "dbColumnName": "dbColumnName",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": " ForeignKey Column Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit": false,
            "togglable": false,
        },
        {
            "dbColumnName": "displayColumnName",
            "htmlControlType": "text",
            "visibility": true,
            "required": true,
            "isComplexType": false,
            "displayName": "Display Column Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "",
            "columnCss": "",
            "allowGridLevelEdit": false,
            "togglable": false,
        }]
};