System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var RoleApplicationMenuItemConfig, RoleApplicationResourceConfig;
    return {
        setters:[],
        execute: function() {
            exports_1("RoleApplicationMenuItemConfig", RoleApplicationMenuItemConfig = {
                ChildType: "editInline",
                ShallHideDeleteButton: false,
                ShallHideAddButton: false,
                PaginationPageLimit: 10,
                ShowFilterRow: true,
                ForeignKeyColumn: "RoleApplicationId",
                IsScrollableGrid: true,
                ColumnConfiguration: [{
                        "dbColumnName": "Id",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Id",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                    },
                    {
                        "dbColumnName": "RoleApplicationId",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Role",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                    },
                    {
                        "dbColumnName": "MenuItemId",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Menu Item",
                        "dataSourceAddress": { tableName: "/auth/menuItem", dbColumnName: "Id", displayColumnName: "LookupKey" },
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                    },
                    {
                        "dbColumnName": "Create",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Create",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Read",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Read",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Update",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Update",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Delete",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Delete",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "VersionStamp",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isComplexType": false,
                        "isRequired": false,
                        "displayName": "VersionStamp",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                    }]
            });
            exports_1("RoleApplicationResourceConfig", RoleApplicationResourceConfig = {
                ChildType: "editInline",
                ShallHideDeleteButton: false,
                ShallHideAddButton: false,
                PaginationPageLimit: 10,
                ShowFilterRow: true,
                ForeignKeyColumn: "RoleApplicationId",
                IsScrollableGrid: true,
                ColumnConfiguration: [{
                        "dbColumnName": "Id",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Id",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                    },
                    {
                        "dbColumnName": "RoleApplicationId",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Role",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                    },
                    {
                        "dbColumnName": "ResourceId",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Resource Name",
                        "dataSourceAddress": { tableName: "/auth/resource", dbColumnName: "Id", displayColumnName: "Name" },
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                    },
                    {
                        "dbColumnName": "Create",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Create",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Read",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Read",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Update",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Update",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "Delete",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Delete",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
                    },
                    {
                        "dbColumnName": "VersionStamp",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isComplexType": false,
                        "isRequired": false,
                        "displayName": "VersionStamp",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                    }]
            });
        }
    }
});
//# sourceMappingURL=applicationRolesConfig.js.map