let BMONB ={
    ChildType:"",
    PrimaryKeyColumn:"",
    ForeignKeyColumn:"",
    ShallHideDeleteBtn:true,
    shallHideAddBtn:true,
    IsChildPage:false,
    PaginationPageLimit:10,
    ColumnConfiguration:[{
        "dbColumnName":"Name",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"CUSIP",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"CUSIP",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"ISIN",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"ISIN",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"TICKER",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"TICKER",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"Duration",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Duration",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SourceID",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Source ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SecurityID",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Security ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"Weight",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Weight",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"Date",
        "htmlControlType":"Date",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    }]
};

let MSCI ={
    ChildType:"",
    PrimaryKeyColumn:"",
    ForeignKeyColumn:"",
    ShallHideDeleteBtn:true,
    shallHideAddBtn:true,
    IsChildPage:false,
    PaginationPageLimit:10,
    ColumnConfiguration:[{
        "dbColumnName":"CUSIP",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"CUSIP",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"Date",
        "htmlControlType":"Date",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"Duration",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Duration",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"ISIN",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"ISIN",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"ISO",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"ISO",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"IndexCurrency",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Index Currency",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"IndexCurrencyFxRate",
        "htmlControlType":"number",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Index FX Rate",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-3"
    },{
        "dbColumnName":"Index_Market_Cap",
        "htmlControlType":"number",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Index Market Cap",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-3"
    },{
        "dbColumnName":"MarketCode",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Market Code",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"Name",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"PriceCurrency",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Price Currency",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"SEDOL",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"SEDOL",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"SecurityID",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Security ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"SharesOutstanding",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Shares Outstanding",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SourceID",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Source ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"TICKER",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Ticker",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    },{
        "dbColumnName":"Weight",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Weight",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"price",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Price",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-2"
    }]
};
let SP ={
    ChildType:"",
    PrimaryKeyColumn:"",
    ForeignKeyColumn:"",
    ShallHideDeleteBtn:true,
    shallHideAddBtn:true,
    IsChildPage:false,
    PaginationPageLimit:10,
    ColumnConfiguration:[{
        "dbColumnName":"SecurityID",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Security ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SourceID",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Source ID",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"Weight",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Weight",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"Duration",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Duration",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"AverageRating",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Average Rating",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"Date",
        "htmlControlType":"datetime-local",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"Name",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"CUSIP",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"CUSIP",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SEDOL",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"SEDOL",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"ISIN",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"ISIN",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"TICKER",
        "htmlControlType":"text",
        "visibility":true,
        "required":true,
        "isComplexType":false,
        "displayName":"TICKER",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":"col-4"
    },{
        "dbColumnName":"SHARE_CUMULATIVE",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Share Cumulative",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"MarketCap",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Market Cap",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"Price",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Price",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"SharesOutstanding",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Shares Outstanding",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"PriceCurrency",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Price Currency",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"IndexCurrency",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Index Currency",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"IndexCurrencyFxRate",
        "htmlControlType":"number",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Index Cur. FX Rate",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    },{
        "dbColumnName":"SecurityNumber",
        "htmlControlType":"text",
        "visibility":false,
        "required":true,
        "isComplexType":false,
        "displayName":"Security Number",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss":""
    }]
};
export var BenchMarkIndexControlConfig = {templateBMONB: BMONB, templateMSCI : MSCI, templateSP : SP};

