"use strict";
exports.RoleApplicationsControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    IsScrollableGrid: true,
    ForeignKeyColumn: "ApplicationId",
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "ApplicationId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Application",
            "dataSourceAddress": { tableName: "/auth/application", dbColumnName: "Id", displayColumnName: "Name" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "RoleId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Role",
            "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Name" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.ApplicationsListControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    IsScrollableGrid: true,
    IsChildPage: "true",
    ChildControlConfig: exports.RoleApplicationsControlConfig,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "LookupKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "LookupKey",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Name",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Name",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": true,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.RolesListControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    RowSelectionMode: "None",
    ShowFilterRow: true,
    ChildGridType: "displayGrid",
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Name",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "External Code",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.MenuItemsConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    //ForeignKeyColumn: "ApplicationId",
    IsScrollableGrid: true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "ApplicationId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Application",
            "dataSourceAddress": { tableName: "/auth/Application", dbColumnName: "Id", displayColumnName: "Name" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "LookupKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "LookupKey",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Route",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Route",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ViewConfig",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "ViewConfig",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Title",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Title",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "MenuType",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Menu Type",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Parameter",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Parameters",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }
    ]
};
exports.ResourcesConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    //PaginationPageLimit: 10,
    IsScrollableGrid: true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Name",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "External Code",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ApiUrl",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "ApiUrl",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.ApplicationRolesConfig = {
    ColumnConfiguration: [
        {
            "dbColumnName": "Application",
            "htmlControlType": "customselect",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "Application Name",
            "dataSourceAddress": { tableName: "/auth/Application", dbColumnName: "Id", displayColumnName: "Name" },
            "dataSource": undefined,
            "regex": undefined
        },
        {
            "dbColumnName": "Role",
            "htmlControlType": "customselect",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "Role",
            "dataSourceAddress": { dbColumnName: "RoleApplicationId", displayColumnName: "Name" },
            "dataSource": undefined,
            "regex": undefined
        }
    ]
};
exports.ApplicationRoleMenuItemConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    ForeignKeyColumn: "RoleApplicationId",
    IsScrollableGrid: true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "RoleApplicationId",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Role",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "MenuItemId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Menu Item",
            "dataSourceAddress": { tableName: "/auth/menuItem", dbColumnName: "Id", displayColumnName: "LookupKey" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Create",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Create",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Read",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Read",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Update",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Update",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Delete",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Delete",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.ApplicationRoleResourceConfig = {
    ChildType: "editInline",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    ForeignKeyColumn: "RoleApplicationId",
    IsScrollableGrid: true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "RoleApplicationId",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Role",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ResourceId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Resource Name",
            "dataSourceAddress": { tableName: "/auth/resource", dbColumnName: "Id", displayColumnName: "Name", isBodyRemoved: true },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Create",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Create",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Read",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Read",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Update",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Update",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "Delete",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Delete",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
exports.ApplicationsListTabConfig = {
    TabsList: [
        {
            TabKey: "Applications",
            TabName: "Applications",
            TabControls: [
                {
                    ShowDefault: true,
                    ComponentName: "ApplicationsList",
                    PageType: "displaygrid",
                    gridSettings: exports.ApplicationsListControlConfig,
                    PageOperationType: 'dynamicform'
                }
            ],
        }, {
            TabKey: "Roles",
            TabName: "Roles List",
            TabControls: [
                {
                    ShowDefault: true,
                    ComponentName: "role",
                    PageType: "displaygrid",
                    gridSettings: exports.RolesListControlConfig,
                    PageOperationType: 'dynamicform'
                }
            ],
        },
        {
            TabKey: "Resources",
            TabName: "Resources",
            TabControls: [
                {
                    ShowDefault: true,
                    ComponentName: "menuitem",
                    PageType: "displaygrid",
                    gridSettings: exports.MenuItemsConfig,
                    PageOperationType: 'dynamicform'
                },
                {
                    ShowDefault: true,
                    ComponentName: "resource",
                    PageType: "displaygrid",
                    gridSettings: exports.ResourcesConfig,
                    PageOperationType: 'dynamicform'
                }
            ],
        },
        {
            TabKey: "ApplicationRoles",
            TabName: "Application Roles",
            TabControls: [
                {
                    ShowDefault: true,
                    ComponentName: "applicationroles",
                    PageType: "formbuilder",
                    gridSettings: exports.ApplicationRolesConfig,
                    PageOperationType: 'dynamicform'
                },
                {
                    ShowDefault: false,
                    ComponentName: "roleapplicationmenuitem",
                    PageType: "displaygrid",
                    gridSettings: exports.ApplicationRoleMenuItemConfig,
                    PageOperationType: 'dynamicform'
                },
                {
                    ShowDefault: false,
                    ComponentName: "roleapplicationresource",
                    PageType: "displaygrid",
                    gridSettings: exports.ApplicationRoleResourceConfig,
                    PageOperationType: 'dynamicform'
                }
            ]
        }
    ]
};
//# sourceMappingURL=applicationsListControlConfig.js.map