export var EncryptionKeyringControlConfig={
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    IsScrollableGrid: true,
    PrimaryKeyColumn: "KeyRingID",
    //ForeignKeyColumn: "ApplicationId",
    ColumnConfiguration: [{
        "dbColumnName": "KeyRingID",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired":false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
    },
        {
            "dbColumnName": "Key",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Key",
            "dataSourceAddress": undefined,
            "dataSource":undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "PublicKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Public Key",
            "dataSourceAddress": undefined,
            "dataSource":undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "PrivateKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Private Key",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "PassPhrase",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": true,
            "isComplexType": false,
            "displayName": "Passphrase",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Active",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Active",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
