export var HolidaySetCodeControlConfig =  {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required":false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":undefined,
        "togglable": false
    },
    {
        "dbColumnName": "Description",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-6",
        "togglable": true,
    },
    {
        "dbColumnName": "ExternalCode",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "External Code",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-9",
        "togglable": false
    },
    {
        "dbColumnName": "IsActive",
        "htmlControlType": "checkbox",
        "visibility": true,
        "isComplexType": false,
        "required":true,
        "displayName": "Active",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-3",
        "togglable": false,
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required":false,
        "displayName": "VersionStamp",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":undefined,
        "togglable": false
    }]
};