let TheChild= {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    ForeignKeyColumn: "MenuItemId",
    PaginationPageLimit: 10,
    ColumnConfiguration:[{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
        {
            "dbColumnName": "RoleId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Role",
            "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "MenuItemId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "MenuItem",
            "dataSourceAddress": { tableName: "/auth/menuitem", dbColumnName: "Id", displayColumnName: "LookupKey" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Create",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Create",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Read",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Read",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Update",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Update",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Delete",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Delete",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};

export var MenuItemControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: true,
    ShallHideAddButton: false,
    IsChildPage: "true",
    ChildControlConfig: TheChild,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    ForeignKeyColumn: "ApplicationId",
    IsScrollableGrid:true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":undefined,
        },
        {
            "dbColumnName": "ApplicationId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Application",
            "dataSourceAddress":{ tableName: "/auth/Application", dbColumnName: "Id", displayColumnName: "Name" },
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "LookupKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "LookupKey",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Route",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Route",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ViewConfig",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "ViewConfig",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":undefined,
        },
        {
            "dbColumnName": "Title",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Title",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "MenuType",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "Menu Type",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Parameter",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "Parameters",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired":false,
            "displayName": "VersionStamp",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":undefined,
        }
    ]
};
