"use strict";
exports.NotificationAlertControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: true,
    ShallHideAddButton: false,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "StartDate",
            "htmlControlType": "datetime-local",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Start Date",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "EndDate",
            "htmlControlType": "datetime-local",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "End Date",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "IsActive",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "Active",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnFormat": { format: "font-awesome", pattern: { false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg' } }
        },
        {
            "dbColumnName": "RoleId",
            "htmlControlType": "select",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "Role",
            "dataSourceAddress": { tableName: "/auth/role", dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "CreatedBy",
            "htmlControlType": "select",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "CreatedBy",
            "dataSourceAddress": { tableName: "/auth/User", dbColumnName: "Id", displayColumnName: "Login" },
            "dataSource": undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
        }]
};
//# sourceMappingURL=notificationAlertControlConfig.js.map