export var DefaultSettingValuesControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: false,
    IsScrollableGrid: true,
    ForeignKeyColumn: "SectionId",
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "SectionId",
        "htmlControlType": "select",
        "isVisible": true,
        "isRequired": true,
        "isComplexType": false,
        "displayName": "Section",
        "dataSourceAddress": { tableName: "/settings/section", dbColumnName: "Id", displayColumnName: "SectionName" },
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "Key",
        "htmlControlType": "text",
        "isVisible": true,
        "isRequired": true,
        "isComplexType": false,
        "displayName": "Key",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "Value",
        "htmlControlType": "text",
        "isVisible": true,
        "isComplexType": false,
        "isRequired": true,
        "displayName": "Value",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "Encrypted",
        "htmlControlType": "checkbox",
        "isVisible": true,
        "isComplexType": false,
        "isRequired": false,
        "displayName": "Encrypted",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "Active",
        "htmlControlType": "checkbox",
        "isVisible": true,
        "isComplexType": false,
        "isRequired": false,
        "displayName": "Active",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    }]
};

export var DefaultSettingsControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    IsScrollableGrid: true,
    IsChildPage: "true",
    ChildControlConfig: DefaultSettingValuesControlConfig,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
    },
    {
        "dbColumnName": "SectionName",
        "htmlControlType": "text",
        "isVisible": true,
        "isRequired": true,
        "isComplexType": false,
        "displayName": "Section Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,200}$",
    }]
};
