System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var TheChild, UserControlConfig;
    return {
        setters:[],
        execute: function() {
            TheChild = {
                ChildType: "edit",
                ShallHideDeleteButton: false,
                ShallHideAddButton: false,
                ForeignKeyColumn: "UserId",
                ColumnConfiguration: [{
                        "dbColumnName": "Id",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Id",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    },
                    {
                        "dbColumnName": "RoleId",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Role",
                        "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Description" },
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnCss": "col-6",
                    },
                    {
                        "dbColumnName": "UserId",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "User",
                        "dataSourceAddress": { tableName: "/auth/User", dbColumnName: "Id", displayColumnName: "Login" },
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnCss": "col-6",
                    },
                    {
                        "dbColumnName": "VersionStamp",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "VersionStamp",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    }]
            };
            exports_1("UserControlConfig", UserControlConfig = {
                ChildType: "editInline",
                ShallHideDeleteButton: false,
                ShallHideAddButton: false,
                IsChildPage: "true",
                ChildControlConfig: TheChild,
                PaginationPageLimit: 4,
                ShowFilterRow: true,
                ColumnConfiguration: [{
                        "dbColumnName": "Id",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Id",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    },
                    {
                        "dbColumnName": "Name",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Name",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnCss": "col-6",
                    },
                    {
                        "dbColumnName": "Login",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "UserName",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "^[a-zA-Z.]{2,30}$",
                        "columnCss": "col-5",
                    },
                    {
                        "dbColumnName": "CostCentre",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Cost Centre",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    },
                    {
                        "dbColumnName": "VersionStamp",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "VersionStamp",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    }]
            });
        }
    }
});
//# sourceMappingURL=userControlConfig.js.map