let TheChild = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ForeignKeyColumn: "RoleId",
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined
    },
    {
        "dbColumnName": "RoleId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Role",
        "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Description" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-6",
    },
    {
        "dbColumnName": "ResourceId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "ApiUrl",
        "dataSourceAddress": { tableName: "/auth/resource", dbColumnName: "Id", displayColumnName: "ApiUrl" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-6",
    },
    {
        "dbColumnName": "Create",
        "htmlControlType": "checkbox",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Create",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "Read",
        "htmlControlType": "checkbox",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Read",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "Update",
        "htmlControlType": "checkbox",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Update",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "Delete",
        "htmlControlType": "checkbox",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Delete",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": true,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }]
};
let TheParent = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    IsChildPage: "true",
    ColumnsList: ["Id", "Description", "Name", "VersionStamp"],
    childControlconfig: TheChild,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required":false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":undefined,
        "displayOrder": 1
    },
    {
        "dbColumnName": "Description",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-6",
        "displayOrder": 3
    },
    {
        "dbColumnName": "Name",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "External Code",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":"^[a-zA-Z.]{2,30}$",
        "columnCss":"col-6",
        "displayOrder": 2
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required":true,
        "displayName": "VersionStamp",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-3",
        "displayOrder": 4
    }]
    };
export var RoleParentChildControlConfig = { theParent : TheParent, theChild: TheChild};



