let TheChild = {
    ChildType: "edit",
    ShallHideDeleteBtn: true,
    shallHideAddBtn: false,
    ForeignKeyColumn: "UnitId",
    PrimaryKeyColumn: "ConfigValueTypeId",
    ColumnConfiguration	:[{
        "dbColumnName": "ConfigValueTypeId",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "ConfigValueTypeId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    {
        "dbColumnName": "MessageTypeId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Message Type",
        "dataSourceAddress": { tableName: "/config/messagetype", dbColumnName: "MessageTypeId", displayColumnName: "LookupKey" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-4",
    },
    {
        "dbColumnName": "UnitId",
        "htmlControlType": "select",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Unit",
        "dataSourceAddress": { tableName: "/config/unit", dbColumnName: "UnitId", displayColumnName: "LookupKey" },
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-3",
    },
    {
        "dbColumnName": "LookupKey",
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-4",
    },
    {
        "dbColumnName": "Template",
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Template",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-6",
        "type": "json"
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": true,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }]
};

export var configunitControlConfig = {
    ChildType: "edit",
    ShallHideDeleteBtn: true,
    shallHideAddBtn: false,
    IsChildPage: "true",
    childControlconfig: TheChild,
    PaginationPageLimit: 10,
    PrimaryKeyColumn: "UnitId",
    ColumnConfiguration: [{
        "dbColumnName": "UnitId",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    {
        "dbColumnName": "LookupKey",
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-10",
    },
    {
        "dbColumnName": "UnitTypeId",
        "htmlControlType": "select",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Unit Type",
        "dataSourceAddress": { tableName: "/config/UnitType", dbColumnName: "UnitTypeId", displayColumnName: "UnitTypeLookupKey"},
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-4",
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": false,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }]
};