export var ControlConfig = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
        {
            "dbColumnName": "EntityId",
            "htmlControlType": "text",
            "visibility": false,
            "required": false,
            "isComplexType": false,
            "displayName": "EntityId",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": undefined,
        },
        {
            "dbColumnName": "EntityTypeId",
            "htmlControlType": "text",
            "visibility": false,
            "required": false,
            "isComplexType": false,
            "displayName": "EntityTypeId",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": undefined,
        },
        {
            "dbColumnName": "IsActive",
            "htmlControlType": "checkbox",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Active",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-1",
        },
        {
            "dbColumnName": "HolidaysSetCodeId",
            "htmlControlType": "radio",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Holiday Description",
            "dataSourceAddress": {tableName: "/schedules/holidayssetcode", dbColumnName: "Id", displayColumnName: "Description"},
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-3",
        },
        {
            "dbColumnName": "HolidayBehaviorId",
            "htmlControlType": "select",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Holiday Behavior",
            "dataSourceAddress": {tableName: "/schedules/holidaybehavior", dbColumnName: "Id", displayColumnName: "Description"},
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-3",
        },
        {
            "dbColumnName": "FirstRunDateTime",
            "htmlControlType": "datetime-local",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "First Run Time",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-3",
        },
        {
            "dbColumnName": "RunWindowStartTime",
            "htmlControlType": "number",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Start Time",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-2",
        },
        {
            "dbColumnName": "RunWindowEndTime",
            "htmlControlType": "number",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "End Time",
            "dataSourceAddress": undefined,
            "regex": undefined,
            "columnCss": "col-2",
        },
        {
            "dbColumnName": "MinutesToNextRun",
            "htmlControlType": "number",
            "visibility": true,
            "isComplexType": false,
            "required": true,
            "displayName": "Time to Run",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-2",
        },
        {
            "dbColumnName": "LookupDaysWhereClause",
            "htmlControlType": "text",
            "visibility": true,
            "isComplexType": true,
            "required": true,
            "displayName": "Lookup Days",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-4",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "visibility": false,
            "isComplexType": false,
            "required": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "columnCss": "col-3",
        }]
}