export var TheChild= {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    ForeignKeyColumn: "ResourceId",
    PaginationPageLimit: 10,
    ColumnConfiguration:[{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
    },
        {
            "dbColumnName": "RoleId",
            "htmlControlType": "select",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Role",
            "dataSourceAddress": { tableName: "/auth/Role", dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ResourceId",
            "htmlControlType": "select",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "ApiUrl",
            "dataSourceAddress": { tableName: "/auth/resource", dbColumnName: "Id", displayColumnName: "ApiUrl" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Create",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "Create",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Read",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Read",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Update",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Update",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "Delete",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Delete",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
        }]
};

export var ResourceControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    IsChildPage: "true",
    PaginationPageLimit: 10,
    ChildControlConfig: TheChild,
    ColumnConfiguration	: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
    },
        {
            "dbColumnName": "Name",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "External Code",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "ApiUrl",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":false,
            "isComplexType": false,
            "displayName": "ApiUrl",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
            "regex":"^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "displayName": "VersionStamp",
            "dataSourceAddress":undefined,
            "dataSource":undefined,
        }]
};
