System.register(["./foreignKeyBuilder"], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var foreignKeyBuilder_1;
    var ConfigBuilderColumnConfig;
    return {
        setters:[
            function (foreignKeyBuilder_1_1) {
                foreignKeyBuilder_1 = foreignKeyBuilder_1_1;
            }],
        execute: function() {
            exports_1("ConfigBuilderColumnConfig", ConfigBuilderColumnConfig = {
                ColumnConfiguration: [
                    {
                        "dbColumnName": "dbColumnName",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Column Name",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "htmlControlType",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Control Type",
                        "dataSourceAddress": { dbColumnName: "Id", displayColumnName: "Description" },
                        "dataSource": [{ Id: "text", Description: "text" }, { Id: "select", Description: "select" }, { Id: "datetime-local", Description: "datetime-local" },
                            { Id: "checkbox", Description: "checkbox" }, { Id: "number", Description: "number" }],
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "isVisible",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Is Visible",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "isRequired",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Is Required",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "isComplexType",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Is Complex Type",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "displayName",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Display Name",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "dataSourceAddress",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": false,
                        "isComplexTypeInline": true,
                        "isComplexTypeInlineTemplate": [{ tableName: "", dbColumnName: "", displayColumnName: "" }],
                        "isComplexTypeInlineTemplateConfig": foreignKeyBuilder_1.ForeignKeyBuilderConfig,
                        "isRequired": true,
                        "displayName": "Foreign Key",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": true,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "dataSource",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": false,
                        "isComplexTypeInline": false,
                        "isRequired": true,
                        "displayName": "Foreign Key Selection",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "regex",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Regular Expression",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": true,
                        "isToggleable": false
                    },
                    {
                        "dbColumnName": "columnCss",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Column CSS Name",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false
                    },
                    {
                        "dbColumnName": "isAllowGridLevelEdit",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Is Allow Grid Level Edit",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    },
                    {
                        "dbColumnName": "isToggleable",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isRequired": true,
                        "isComplexType": false,
                        "displayName": "Is Toggleable",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": "",
                        "columnCss": "",
                        "isAllowGridLevelEdit": false,
                        "isToggleable": false,
                    }]
            });
        }
    }
});
//# sourceMappingURL=configBuilderColumnConfig.js.map