export var ConnectionStringControlConfig={
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    IsScrollableGrid: true,
    PrimaryKeyColumn: "ID",
    ColumnConfiguration: [{
        "dbColumnName": "ID",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired":false,
        "isComplexType": false,
        "displayName": "ID",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
    },
        {
            "dbColumnName": "DataKey",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Data Key",
            "dataSourceAddress": undefined,
            "dataSource":undefined,
            "regex": undefined,
        },
        {
            "dbColumnName": "Connection",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired":true,
            "isComplexType": false,
            "displayName": "Connection String",
            "dataSourceAddress": undefined,
            "dataSource":undefined,
            "regex": undefined,
        }]
};
