let TheChild = {
    Name:"OldLogs",
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ColumnsList: ["LoggingId", "InstanceId", "ApplicationId", "State", "Date", "Level", "Logger", "Message", "MachineName", "UserName", "CallSite", "Thread", "Exception", "Stacktrace" , "VersionStamp"],
    ForeignKeyColumn: "InstanceId",
    "LoggingId": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "LoggingId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "InstanceId": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "InstanceId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "ApplicationId": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "ApplicationId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "State": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "State",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Date": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Level": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Level",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Logger": {
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Logger",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Message": {
        "htmlControlType": "text",
        "visibility": false,
        "required": true,
        "isComplexType": false,
        "displayName": "Message",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "MachineName": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "MachineName",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "UserName": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "UserName",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "CallSite": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "CallSite",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Thread": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Thread",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Exception": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Exception",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "Stacktrace": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Stacktrace",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    "VersionStamp": {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }
};

export var LogsControlConfig = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    IsChildPage: "true",
    childControlconfig: TheChild,
    PaginationPageLimit: 10,
   // ChildType: "view",
   // PaginationPageLimit: 10,
    InstanceId: {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "InstanceId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-1"
    },
    ApplicationId: {
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "ApplicationId",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined
    },
    Logger: {
        "htmlControlType": "Logger",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Logger",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined
    },
    MachineName: {
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Machine Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-2"
    },
    UserName: {
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": true,
        "displayName": "User Name",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined
    },
    Start: {
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Start",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-5"
    },
    End: {
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "End",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-5"
    },
    State: {
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "State",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3"
    },
    MaxLevel: {
        "htmlControlType": "text",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Max Level",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3"
    },
};