export var HolidayControlConfig = {
    ChildType: "editInline",
    ShallHideDeleteBtn: false,
    IsSpreadsheetGrid:true,
    shallHideAddBtn: false,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
        "allowGridLevelEdit":false,
    },
    {
        "dbColumnName": "Description",
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-5",
        "allowGridLevelEdit":true,
    },
    {
        "dbColumnName": "HolidayDate",
        "htmlControlType": "datetime-local",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Holiday Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-5",
        "allowGridLevelEdit":true,
    },
     {
        "dbColumnName": "HolidaysSetCodeId",
        "htmlControlType": "select",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Holiday Set Code",
        "dataSourceAddress": {tableName: "/schedules/holidayssetcode", dbColumnName: "Id", displayColumnName: "Description"},
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-4",
        "allowGridLevelEdit":true,
        "togglable": false
    },
     {
        "dbColumnName": "IsActive",
        "htmlControlType": "checkbox",
        "visibility": true,
        "isComplexType": false,
        "required": true,
        "displayName": "Active",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3",
        "allowGridLevelEdit":true,
        "togglable": true
    },
     {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": false,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3",
        "allowGridLevelEdit":false,
    }]
};