export var ProcessDesignerConfig = {
    ChildType: "edit",
    ShallHideDeleteBtn: false,
    shallHideAddBtn: false,
    ColumnConfiguration	:[{
        "dbColumnName": "StepNo",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Step Number",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-4",
    },
    {
    "dbColumnName": "UnitName",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Unit Name",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-4",
    },
    {
        "dbColumnName": "ConfigurationTypeName",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Configuration Type",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-4",
    },
    {
        "dbColumnName": "ConfigurationTypeValue",
        "htmlControlType": "text",
        "visibility": true,
        "required":false,
        "isComplexType": false,
        "displayName": "Configuration Type Value",
        "dataSourceAddress":undefined,
        "dataSource":undefined,
        "regex":undefined,
        "columnCss":"col-4",
    }]
};