System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var ControlConfig;
    return {
        setters:[],
        execute: function() {
            exports_1("ControlConfig", ControlConfig = {
                ChildType: "edit",
                ShallHideDeleteButton: false,
                ShallHideAddButton: false,
                ColumnConfiguration: [{
                        "dbColumnName": "Id",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "Id",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    },
                    {
                        "dbColumnName": "EntityId",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "EntityId",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    },
                    {
                        "dbColumnName": "EntityTypeId",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isRequired": false,
                        "isComplexType": false,
                        "displayName": "EntityTypeId",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": undefined,
                    },
                    {
                        "dbColumnName": "IsActive",
                        "htmlControlType": "checkbox",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Active",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-1",
                    },
                    {
                        "dbColumnName": "HolidaysSetCodeId",
                        "htmlControlType": "radio",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Holiday Description",
                        "dataSourceAddress": { tableName: "/schedules/holidayssetcode", dbColumnName: "Id", displayColumnName: "Description" },
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    },
                    {
                        "dbColumnName": "HolidayBehaviorId",
                        "htmlControlType": "select",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Holiday Behavior",
                        "dataSourceAddress": { tableName: "/schedules/holidaybehavior", dbColumnName: "Id", displayColumnName: "Description" },
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    },
                    {
                        "dbColumnName": "FirstRunDateTime",
                        "htmlControlType": "datetime-local",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "First Run Time",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    },
                    {
                        "dbColumnName": "RunWindowStartTime",
                        "htmlControlType": "number",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Start Time",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-2",
                    },
                    {
                        "dbColumnName": "RunWindowEndTime",
                        "htmlControlType": "number",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "End Time",
                        "dataSourceAddress": undefined,
                        "regex": undefined,
                        "columnCss": "col-2",
                    },
                    {
                        "dbColumnName": "MinutesToNextRun",
                        "htmlControlType": "number",
                        "isVisible": true,
                        "isComplexType": false,
                        "isRequired": true,
                        "displayName": "Time to Run",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-2",
                    },
                    {
                        "dbColumnName": "LookupDaysWhereClause",
                        "htmlControlType": "text",
                        "isVisible": true,
                        "isComplexType": true,
                        "isRequired": true,
                        "displayName": "Lookup Days",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-4",
                    },
                    {
                        "dbColumnName": "VersionStamp",
                        "htmlControlType": "text",
                        "isVisible": false,
                        "isComplexType": false,
                        "isRequired": false,
                        "displayName": "VersionStamp",
                        "dataSourceAddress": undefined,
                        "dataSource": undefined,
                        "regex": undefined,
                        "columnCss": "col-3",
                    }]
            });
        }
    }
});
//# sourceMappingURL=controlConfig.js.map