let TheChild = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    ForeignKeyColumn: "ValueSetId",
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,

            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,

        },
        {
            "dbColumnName": "ValueSetId",
            "htmlControlType": "select",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "ValueSet Description",
            "dataSourceAddress": { tableName: "/localization/valueSet", dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "LanguageId",
            "htmlControlType": "select",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "Language",
            "dataSourceAddress": { tableName: "/Localization/language", dbColumnName: "Id", displayColumnName: "Description" },
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "Value",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "isAllowGridLevelEdit":true,
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined
        }]
};

export var ValueSetControlConfig = {
    ChildType: "editInline",
    ShallHideDeleteButton: false,
    ShallHideAddButton: false,
    IsChildPage: "true",
    ChildControlConfig: TheChild,
    PaginationPageLimit: 10,
    ShowFilterRow: true,
    ColumnConfiguration: [{
            "dbColumnName": "Id",
            "htmlControlType": "text",
            "isVisible": false,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Id",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "isAllowGridLevelEdit":false,
        },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "isAllowGridLevelEdit":true,
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "isAllowGridLevelEdit":false,
        }]
};