/*export var treeViewMainConfig={
    "ColumnConfiguration":[
        {
            "dbColumnName":"CustomerId",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Customer Id",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"FirstName",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"First Name",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"LastName",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Last Name",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"EquityId",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Equity Id",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"Holdings",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Holdings",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"Stock",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Stock",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"AddressId",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Address Id",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"AddressType",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Address Type",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"StreetAddress1",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Street Address 1",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"City",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"City",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"Province",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Province",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"HoldingId",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Holding Id",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"Name",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Name",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
        {
            "dbColumnName":"Price",
            "htmlControlType":"text",
            "visibility":true,
            "required":true,
            "isComplexType":false,
            "displayName":"Price",
            "dataSourceAddress":"",
            "dataSource":"",
            "regex":"",
            "columnCss":"",
            "allowGridLevelEdit":false,
            "togglable": false,
        },
    ]
};*/


export var treeViewMainConfig={
    "RootModel": "Customer",
    "Definitions": [
        {
            "ModelName": "Customer",
            "ColumnDefinitions": [
                {
                    "dbColumnName": "Customer_Id",
                    "htmlControlType": "text",
                    "visibility": false,
                    "required": false,
                    "isComplexType": false,
                    "displayName": "Id",
                    "regex": null,
                    "columnCss": null
                },
                {
                    "dbColumnName": "FirstName",
                    "htmlControlType": "text",
                    "visibility": false,
                    "required": false,
                    "isComplexType": false,
                    "displayName": "FirstName",
                    "regex": "^[a-zA-Z.]{2,30}$",
                    "columnCss": "col-3"
                },
                {
                    "dbColumnName": "LastName",
                    "htmlControlType": "text",
                    "visibility": false,
                    "required": false,
                    "isComplexType": false,
                    "displayName": "LastName",
                    "regex": "^[a-zA-Z.]{2,30}$",
                    "columnCss": "col-3"
                }
            ],
            "NodeModels": [
                "Address","Equity"
            ]
        },
        {
            "ModelName": "Address",
            "NodeClass":"tdam-panel",
            "ColumnDefinitions": [
                {
                    "dbColumnName":"AddressId",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Address Id",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"AddressType",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Address Type",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"StreetAddress1",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Street Address 1",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"City",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"City",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"Province",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Province",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                }
            ],
            "NodeModels": [
            ]
        },
        {
            "ModelName": "Equity",
            "NodeClass":"tdam-panel",
            "ColumnDefinitions": [
                {
                    "dbColumnName":"EquityId",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Equity Id",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"Stock",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Stock",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
            ],
            "NodeModels": [
                "Holdings"
            ]
        },
        {
            "ModelName": "Holdings",
            "NodeClass": "tdam-panel-blue pull-left",
            "ColumnDefinitions": [
                {
                    "dbColumnName":"HoldingId",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Holding Id",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"Name",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Name",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"Price",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"Price",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
            ],
            "NodeModels": [
                "ThirdLevel"
            ]
        },
        {
            "ModelName": "ThirdLevel",
            "NodeClass": "tdam-panel-red pull-right",
            "ColumnDefinitions": [
                {
                    "dbColumnName":"ThirdLevel1",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"ThirdLevel1",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                },
                {
                    "dbColumnName":"ThirdLevel2",
                    "htmlControlType":"text",
                    "visibility":true,
                    "required":true,
                    "isComplexType":false,
                    "displayName":"ThirdLevel2",
                    "dataSourceAddress":"",
                    "dataSource":"",
                    "regex":"",
                    "columnCss":"",
                    "allowGridLevelEdit":false,
                    "togglable": false,
                }
            ],
            "NodeModels": [
            ]
        }
    ]
}

