export var HolidayControlConfig = {
    ChildType: "edit",
    ShallHideDeleteButton: false,
    IsSpreadsheetGrid:false,
    PaginationPageLimit: 5,
    ShallHideAddButton: false,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "isVisible": false,
        "isRequired": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "isAllowGridLevelEdit":false,
    },
        {
            "dbColumnName": "Description",
            "htmlControlType": "text",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Description",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": "^[a-zA-Z.]{2,30}$",
            "isAllowGridLevelEdit":true,
        },
        {
            "dbColumnName": "HolidayDate",
            "htmlControlType": "datetime-local",
            "isVisible": true,
            "isRequired": false,
            "isComplexType": false,
            "displayName": "Holiday Date",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "isAllowGridLevelEdit":true,
        },
        {
            "dbColumnName": "HolidaysSetCodeId",
            "htmlControlType": "radio",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": true,
            "displayName": "Holiday Set Code",
            "dataSourceAddress": {tableName: "/schedules/holidayssetcode", dbColumnName: "Id", displayColumnName: "Description"},
            "dataSource": undefined,
            "regex": undefined,
            "isAllowGridLevelEdit":true,
            "isToggleable": false
        },
        {
            "dbColumnName": "IsActive",
            "htmlControlType": "checkbox",
            "isVisible": true,
            "isComplexType": false,
            "isRequired": true,
            "displayName": "Active",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "isAllowGridLevelEdit":true,
            "isToggleable": true,
            "columnFormat": {format:"font-awesome",pattern:{false: 'fa fa-remove fa-lg', true: 'fa fa-check fa-lg'}}
        },
        {
            "dbColumnName": "VersionStamp",
            "htmlControlType": "text",
            "isVisible": false,
            "isComplexType": false,
            "isRequired": false,
            "displayName": "VersionStamp",
            "dataSourceAddress": undefined,
            "dataSource": undefined,
            "regex": undefined,
            "isAllowGridLevelEdit":false,
        }]
};