export var NotificationAlertControlConfig = {
    ChildType: "edit",
    ShallHideDeleteBtn: true,
    shallHideAddBtn: false,
    ColumnConfiguration: [{
        "dbColumnName": "Id",
        "htmlControlType": "text",
        "visibility": false,
        "required": false,
        "isComplexType": false,
        "displayName": "Id",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    },
    {
        "dbColumnName": "Description",
        "htmlControlType": "text",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Description",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": "^[a-zA-Z.]{2,30}$",
        "columnCss": "col-5",
    },
    {
        "dbColumnName": "StartDate",
        "htmlControlType": "datetime-local",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "Start Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3",
    },
    {
        "dbColumnName": "EndDate",
        "htmlControlType": "datetime-local",
        "visibility": true,
        "required": false,
        "isComplexType": false,
        "displayName": "End Date",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-3",
    },
    {
        "dbColumnName": "IsActive",
        "htmlControlType": "checkbox",
        "visibility": true,
        "isComplexType": false,
        "required": false,
        "displayName": "Active",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "RoleId",
        "htmlControlType": "select",
        "visibility": true,
        "isComplexType": false,
        "required": false,
        "displayName": "Role",
        "dataSourceAddress": {tableName: "/auth/role", dbColumnName: "Id", displayColumnName: "Description"},
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "CreatedBy",
        "htmlControlType": "select",
        "visibility": true,
        "isComplexType": false,
        "required": false,
        "displayName": "CreatedBy",
        "dataSourceAddress": { tableName: "/auth/User", dbColumnName: "Id", displayColumnName: "Login" },
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": "col-2",
    },
    {
        "dbColumnName": "VersionStamp",
        "htmlControlType": "text",
        "visibility": false,
        "isComplexType": false,
        "required": false,
        "displayName": "VersionStamp",
        "dataSourceAddress": undefined,
        "dataSource": undefined,
        "regex": undefined,
        "columnCss": undefined,
    }]
};